name: Deploy to EC2

on:
  push:
    branches:
      - main # Adjust this as necessary for your workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Copy files to SERVER
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ dev@139.59.41.3:/home/dev/api/social-redis
